export const CardsBase = [
	{id: 1, title: "Hello"},
	{id: 2, title: "Hello"},
	{id: 3, title: "Hello"},
	{id: 4, title: "Hello"},
	{id: 5, title: "Hello"},
	{id: 6, title: "Hello"},
	{id: 7, title: "Hello"},
	{id: 8, title: "Hello"},
	{id: 9, title: "Hello"},
	{id: 10, title: "Hello"},
	{id: 11, title: "Hello"},
	{id: 12, title: "Hello"},
	{id: 13, title: "Hello"},
	{id: 14, title: "Hello"},
	{id: 15, title: "Hello"},
	{id: 16, title: "Hello"},
	{id: 17, title: "Hello"},
	{id: 18, title: "Hello"},
];